In [48]:

import pandas as pd

df = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\01_fund_master.csv")
print("Top 5 rows and columns of the dataset : \n",df.head())
print("Shape of the dataset : \n",df.shape)
print("Data types of the dataset : \n",df.dtypes)
print("Columns of the dataset : \n",df.columns)

Top 5 rows and columns of the dataset :
    amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02
Shape of the dataset :
 (40, 15)
Data types of the dataset :
 amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object
Columns of the dataset :
 Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [5]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [6]:
df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [7]:
df.shape

(40, 15)

In [8]:
df.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [49]:
df1 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\02_nav_history.csv")
print("Top 5 rows and columns of the dataset : \n",df1.head())
print("Shape of the dataset : \n",df1.shape)
print("Data types of the dataset : \n",df1.dtypes)
print("Columns of the dataset : \n",df1.columns)

Top 5 rows and columns of the dataset :
    amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692
Shape of the dataset :
 (46000, 3)
Data types of the dataset :
 amfi_code      int64
date             str
nav          float64
dtype: object
Columns of the dataset :
 Index(['amfi_code', 'date', 'nav'], dtype='str')

In [12]:
df1.head

<bound method NDFrame.head of        amfi_code        date       nav
0         119551  2022-01-03   54.3856
1         119551  2022-01-04   54.3474
2         119551  2022-01-05   54.6869
3         119551  2022-01-06   55.4550
4         119551  2022-01-07   55.3692
...          ...         ...       ...
45995     149324  2026-05-25  292.4810
45996     149324  2026-05-26  291.2707
45997     149324  2026-05-27  288.8007
45998     149324  2026-05-28  280.6873
45999     149324  2026-05-29  279.7511

[46000 rows x 3 columns]>

In [13]:
df1.shape

(46000, 3)

In [14]:
df1.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [15]:
df1.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [50]:
df2 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\03_aum_by_fund_house.csv")
print("Top 5 rows and columns of the dataset : \n",df2.head())
print("Shape of the dataset : \n",df2.shape)
print("Data types of the dataset : \n",df2.dtypes)
print("Columns of the dataset : \n",df2.columns)

Top 5 rows and columns of the dataset :
          date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168
Shape of the dataset :
 (90, 5)
Data types of the dataset :
 date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object
Columns of the dataset :
 Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

In [30]:
df2.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [31]:
df2.shape

(90, 5)

In [32]:
df2.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [33]:
df2.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

In [51]:
df3 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\04_monthly_sip_inflows.csv")
print("Top 5 rows and columns of the dataset : \n",df3.head())
print("Shape of the dataset : \n",df3.shape)
print("Data types of the dataset : \n",df3.dtypes)
print("Columns of the dataset : \n",df3.columns)

Top 5 rows and columns of the dataset :
      month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN
Shape of the dataset :
 (48, 6)
Data types of the dataset :
 month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object
Columns of the dataset :
 Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='str')

In [35]:
df3.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [36]:
df3.shape

(48, 6)

In [37]:
df3.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [38]:
df3.columns

Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='str')

In [42]:
df4 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\05_category_inflows.csv")
print("Top 5 rows and columns of the dataset : \n",df4.head())
print("Shape of the dataset : \n",df4.shape)
print("Data types of the dataset : \n",df4.dtypes)
print("Columns of the dataset : \n",df4.columns)

Top 5 rows and columns of the dataset :
      month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0
Shape of the dataset :
 (144, 3)
Data types of the dataset :
 month                   str
category                str
net_inflow_crore    float64
dtype: object
Columns of the dataset :
 Index(['month', 'category', 'net_inflow_crore'], dtype='str')

In [43]:
df5 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\06_industry_folio_count.csv")
print("Top 5 rows and columns of the dataset : \n",df5.head())
print("Shape of the dataset : \n",df5.shape)
print("Data types of the dataset : \n",df5.dtypes)
print("Columns of the dataset : \n",df5.columns)

Top 5 rows and columns of the dataset :
      month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48
Shape of the dataset :
 (21, 6)
Data types of the dataset :
 month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object
Columns of the dataset :
 Index(['month', 'total_folios_crore', 'equity_folios_crore',
       'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore'],
      dtype='str')

In [44]:
df6 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\07_scheme_performance.csv")
print("Top 5 rows and columns of the dataset : \n",df6.head())
print("Shape of the dataset : \n",df6.shape)
print("Data types of the dataset : \n",df6.dtypes)
print("Columns of the dataset : \n",df6.columns)

Top 5 rows and columns of the dataset :
    amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low
Shape of the dataset :
 (40, 19)
Data types of the dataset :
 amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object
Columns of the dataset :
 Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [45]:
df7 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\08_investor_transactions.csv")
print("Top 5 rows and columns of the dataset : \n",df7.head())
print("Shape of the dataset : \n",df7.shape)
print("Data types of the dataset : \n",df7.dtypes)
print("Columns of the dataset : \n",df7.columns)

Top 5 rows and columns of the dataset :
   investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending
Shape of the dataset :
 (32778, 13)
Data types of the dataset :
 investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object
Columns of the dataset :
 Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [46]:
df8 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\09_portfolio_holdings.csv")
print("Top 5 rows and columns of the dataset : \n",df8.head())
print("Shape of the dataset : \n",df8.shape)
print("Data types of the dataset : \n",df8.dtypes)
print("Columns of the dataset : \n",df8.columns)

Top 5 rows and columns of the dataset :
    amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31
Shape of the dataset :
 (322, 8)
Data types of the dataset :
 amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object
Columns of the dataset :
 Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')

In [47]:
df9 = pd.read_csv("C:\\Users\\p00za\\Desktop\\Code files\\CSV File\\10_benchmark_indices.csv")
print("Top 5 rows and columns of the dataset : \n",df9.head())
print("Shape of the dataset : \n",df9.shape)
print("Data types of the dataset : \n",df9.dtypes)
print("Columns of the dataset : \n",df9.columns)

Top 5 rows and columns of the dataset :
          date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15
Shape of the dataset :
 (8050, 3)
Data types of the dataset :
 date               str
index_name         str
close_value    float64
dtype: object
Columns of the dataset :
 Index(['date', 'index_name', 'close_value'], dtype='str')